name: ci

on:
  push:
    branches: [ main, dev ]
  pull_request:
      branches: [ main ]

jobs:

    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        - name: install gtest
          run: sudo apt install libgtest-dev

        - name: build
          run: mkdir build && cd build && cmake .. && cmake --build .

        - name: run-tests
          run: ./tests/tests
