name: ci

on:
  push:
    branches: [  dev ]
  pull_request:
    branches: [ main, dev ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install gtest
        run: sudo apt install libgtest-dev lcov

      - name: build
        run: mkdir build && cd build && cmake .. && cmake --build .

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install gtest
        run: sudo apt install libgtest-dev lcov

      - name: build
        run:  mkdir build && cd build && cmake .. && cmake --build . && ./tests/tests

      - name: get-stats
        run: lcov -t "tests" -o coverage.info -c -d .

      - name: genhtml
        run: genhtml -o report coverage.info
